const Map<String, List<String>> subcategoryAliases = {
  "tshirts": ["tshirt", "tshirts", "t shirt", "tee", "tees"],
  "shirts": ["shirt", "shirts"],
  "jeans": ["jeans", "denim", "pant", "pants"],
  "sandals": ["sandal", "sandals", "flipflops", "flipflop"],
  "handbags": ["handbag", "handbags", "bag", "bags"],
  "shoes": ["shoe", "shoes", "sneaker", "sneakers", "sports-shoes"],
  "tops": ["top", "tops"],
  "dresses": ["dress", "dresses", "frocks"],
  "shorts": ["short", "shorts"],
  "skirts": ["skirt", "skirts"],
  "jackets": ["jacket", "jackets", "coat", "coats"],
  "sarees": ["saree", "sarees"],
  "kurtas": ["kurta", "kurtas"],
  "kurtis": ["kurti", "kurtis"],
  "watches": ["watch", "watches"],
  "perfumes": ["perfume", "perfumes", "deo", "deodorant"],
  "bags": ["bag", "bags", "backpack", "backpacks"],
};
